// STORE TYPES
export const STORE_STREAMS = 'STORE_STREAMS';
export const STORE_RECORDER_SETTINGS = 'STORE_RECORDER_SETTINGS';
export const STORE_SCHEDULER_SETTINGS = 'STORE_SCHEDULER_SETTINGS';
export const SET_STREAM_ERROR = 'SET_STREAM_ERROR';

// RECORDER
export const SET_RECORDER_TO_STREAM = 'SET_RECORDER_TO_STREAM';
