// ACTION TYPES
export const STORE_STREAMS = 'STORE_STREAMS';
export const STORE_RECORDER_SETTINGS = 'STORE_RECORDER_SETTINGS';
export const STORE_SCHEDULER_SETTINGS = 'STORE_SCHEDULER_SETTINGS';
export const SET_STREAM_ERROR = 'SET_STREAM_ERROR';

// RECORDER
export const SET_RECORDER = 'SET_RECORDER';
export const UPDATE_RECORDER = 'UPDATE_RECORDER';
export const REMOVE_RECORDER = 'REMOVE_RECORDER';
export const FINISHED_RECORD = 'FINISHED_RECORD';
export const PUSH_LOG_TO_RECORDER = 'PUSH_LOG_TO_RECORDER';
export const UPDATE_RECORDER_FIELD = 'UPDATE_RECORDER_FIELD';
