// ACTION TYPES
exports.STORE_STREAMS = 'STORE_STREAMS';
exports.STORE_RECORDER_SETTINGS = 'STORE_RECORDER_SETTINGS';
exports.STORE_SCHEDULER_SETTINGS = 'STORE_SCHEDULER_SETTINGS';
exports.SET_STREAM_ERROR = 'SET_STREAM_ERROR';

// RECORDER
exports.SET_RECORDER = 'SET_RECORDER';
exports.UPDATE_RECORDER = 'UPDATE_RECORDER';
exports.REMOVE_RECORDER = 'REMOVE_RECORDER';
exports.FINISHED_RECORD = 'FINISHED_RECORD';
exports.PUSH_LOG_TO_RECORDER = 'PUSH_LOG_TO_RECORDER';
exports.UPDATE_RECORDER_FIELD = 'UPDATE_RECORDER_FIELD';
